# Generated by Django 6.1.1 on 2026-10-01 08:10

from django.db import migrations, models


def copy_teacher_fk_to_m2m(apps, schema_editor):
    Student = apps.get_model("school", "Student")

    for student in Student.objects.all():
        teacher_id = getattr(student, "teacher_id", None)
        if teacher_id:
            student.teachers.add(teacher_id)


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="school.teacher"
            ),
        ),

        migrations.RunPython(copy_teacher_fk_to_m2m, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),

        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=10, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=10, verbose_name='Предмет'),
        ),
    ]